name: 'Test'

on:
  push:
    branches:
      - main
      - release/**
  pull_request:

jobs:
  qa:
    name: Code Quality Assurance
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '22.8.0'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: 'poetry'

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: 1.8.0

      - name: Cache Ruff
        uses: actions/cache@v4
        with:
          path: .ruff_cache
          key: ${{ runner.os }}-ruff-${{ hashFiles('.ruff_cache/CACHEDIR.TAG') }}

      - name: Cache Mypy
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-mypy-${{ hashFiles('.mypy_cache/CACHEDIR.TAG') }}

      - name: Run QA
        run: |
          make qa
